<a href="https://colab.research.google.com/github/ZiadSakr5/ZezoSakr/blob/develop/Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [2]:
import numpy as np
print(np.array([0,1,2,3,4,5,6,7,8,9]))
print(np.zeros((3,3)))
print(np.ones((2,4)))
print(np.eye(3))

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

(2, 3)
int64
2
6



## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:2])

print(arr[:,2])

print(arr[1,2])

print(arr[::-1])

[[10 20 30]
 [40 50 60]]
[30 60 90]
60
[[70 80 90]
 [40 50 60]
 [10 20 30]]



---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [5]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print(arr[arr%2==0])
print(arr[1:3])
print(arr[:,2:])
print(arr[1:3,1:3])

[ 2  4  6  8 10 12 14 16]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 6  7]
 [10 11]]



---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 * arr2)
print(arr2 ** 2)

[5 7 9]
[ 4 10 18]
[16 25 36]



## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [7]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1], [2]])
print(A+B)
print(A*B)
print(A-3)
print(A+C)

[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]
[[-2 -1  0]
 [ 1  2  3]]
[[2 3 4]
 [6 7 8]]



---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [8]:
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])
print(A+B)
print(B*C)
print(A+10)

[[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
[[ 200  400  600  800]
 [ 300  600  900 1200]
 [ 400  800 1200 1600]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]



---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [9]:
arr = np.arange(12)
arr_reshaped = arr.reshape(3, 4)
print(arr_reshaped)


arr_flattened = arr_reshaped.flatten()
print( arr_flattened)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]



---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [12]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

v_stacked = np.vstack((a, b))
print("Vertical stack (shape {}):\n{}".format(v_stacked.shape, v_stacked))

h_stacked = np.hstack((a, b))
print("Horizontal stack (shape {}):\n{}".format(h_stacked.shape, h_stacked))

m = np.arange(1, 17).reshape(4, 4)
print("Original (4x4):\n", m, "\n")

m_reshaped = m.reshape(2, 8)
print("Reshaped to (2,8):\n", m_reshaped)



top, bottom = np.split(m, 2, axis=0)
print("Split into two (2,4) arrays:")
print("Top:\n", top)
print("Bottom:\n", bottom)


Vertical stack (shape (4, 2)):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack (shape (2, 4)):
[[1 2 5 6]
 [3 4 7 8]]
Original (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

Reshaped to (2,8):
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Split into two (2,4) arrays:
Top:
 [[1 2 3 4]
 [5 6 7 8]]
Bottom:
 [[ 9 10 11 12]
 [13 14 15 16]]



## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [19]:
arr = np.array([[5, 10, 15], [20, 25, 30]])
print( arr)

mask_gt_10 = arr > 10
print(mask_gt_10)
print( arr[mask_gt_10])


mask_even = arr % 2 == 0
arr[mask_even] = -1
print(arr)

[[ 5 10 15]
 [20 25 30]]
[[False False  True]
 [ True  True  True]]
[15 20 25 30]
[[ 5 -1 15]
 [-1 25 -1]]



---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)

total_sum = np.sum(arr)
print("\nSum of all elements:", total_sum)

column_mean = np.mean(arr, axis=0)
print("Mean of each column:", column_mean)

row_max = np.max(arr, axis=1)
print("Max value in each row:", row_max)

std_dev = np.std(arr)
print(f"Standard deviation of the array: {std_dev:.2f}")

Original array:
 [[1 2 3]
 [4 5 6]]

Sum of all elements: 21
Mean of each column: [2.5 3.5 4.5]
Max value in each row: [3 6]
Standard deviation of the array: 1.71



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [14]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

dot_product = np.dot(A, B)
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nDot product of A and B:\n", dot_product)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Dot product of A and B:
 [[19 22]
 [43 50]]



---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [16]:
random_floats = np.random.rand(2, 3)
print(random_floats)

random_integers = np.random.randint(50, 101, size=10)
print("\n10 random integers between 50 and 100:\n", random_integers)

[[0.54086163 0.36703414 0.04560969]
 [0.04036482 0.55770559 0.19551464]]

10 random integers between 50 and 100:
 [100  90  71  78  89  92  74  70  99  67]



---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [17]:
from numpy.linalg import matrix_rank, inv, det

matrix = np.array([[1, 2], [3, 4]])
print("Original Matrix:\n", matrix)

rank = matrix_rank(matrix)
print("\nRank of the matrix:", rank)

inverse_matrix = inv(matrix)
print("\nInverse of the matrix:\n", inverse_matrix)

determinant = det(matrix)
print(f"\nDeterminant of the matrix: {determinant:.2f}")

Original Matrix:
 [[1 2]
 [3 4]]

Rank of the matrix: 2

Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of the matrix: -2.00



## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [20]:
original_matrix = np.arange(36).reshape(6, 6)
print("Original 6x6 Matrix:\n", original_matrix)

submatrices = []

rows, cols = original_matrix.shape

for i in range(rows - 2):
    for j in range(cols - 2):
        submatrix = original_matrix[i:i+3, j:j+3]
        submatrices.append(submatrix)

print("\nSubmatrix 1:\n", submatrices[0])
print("\nSubmatrix 2:\n", submatrices[1])

Original 6x6 Matrix:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Submatrix 1:
 [[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]

Submatrix 2:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]



---

Happy coding! 🎯
